### ISSUE TITLE
Question: What happends when eeprom byte is set but file not exist?

### ISSUE THREAD

**Issue by Apollon77** [FleetProbe/MicroBridge-Arduino-ATMega2560#1]
Hi,

can you tell me what happends when the bit it set but the file does not exist on sd card?

**Comment by Mesger1** [comment]
Hello,

It seems if there's no file the bootloader will check each time a reset is
triggered to see if the file is there, only when the file is found and
after the file has been put in program area then will the eeprom flag be
set to default and thus not check for the file again.

We are using a flash chip now to update remotely, there' s other branches
who support this.

Kind regards,

Gerd

**Comment by Apollon77** [comment]
Thanks. I have a standard Arduino ... can I use the version with flash chip too? Which branch is it?

**Comment by Mesger1** [comment]
You need an external flash chip for this. This is a seperate chip which
will require some circuitry made by yourself. The only thing i can
recommend is look up the datasheet of such a chip and learn from it.

The bootloader only works for the mega2560.

**Comment by Apollon77** [comment]
Ok, then i would go with sd card because i already have it on my ethernet shield :-) so version from master is correct one i assume ... or ?!
And yes I have an Mega 2560...
BTW: I found he branch with from-flash ... but there is no real example and also readme is identical to sdcard one ... would help I think ...

**Comment by Mesger1** [comment]
Use master then, you might have to adjust the cs pin when you use the
ethernet shield

**Comment by Apollon77** [comment]
CS for Sd card is pin 4 as I know ...

**Comment by Mesger1** [comment]
You should set the cs pin correctly in asmfunc.s. It is defined there under
the ethernet comment but i had changed it to work with our own shields.

**Comment by Apollon77** [comment]
Can you tell me what would be correct for Mega2560 pin 4 ? In Pinout I found "PG5" for pin 4 ... I would assume the following then:
#define DDR_CS  _SFR_IO_ADDR(DDRG), 5   // MMC CS pin (DDR, PORT)
#define PORT_CS _SFR_IO_ADDR(PORTG), 5

correct?!

**Comment by Mesger1** [comment]
PORTG 5 is digital pin 4 yes
