### ISSUE TITLE
Error Loading Board in new Arduino IDE v1.6.5

### ISSUE THREAD

**Issue by Apollon77** [FleetProbe/MicroBridge-Arduino-ATMega2560#2]
I have copied the "hardware"-Filder to my Arduino dir and restarted IDE (v1.6.5). Now I got the following error in IDE as soon as I open the "Bard manager":

Could not find boards.txt in /Users/.../Arduino/hardware/microbridge/bootloaders. Is it pre-1.5?
WARNING: Error loading hardware folder /Users/...Arduino/hardware/microbridge
  No valid hardware definitions found in folder microbridge.
Could not find boards.txt in /Users/.../Arduino/hardware/microbridge/bootloaders. Is it pre-1.5?
WARNING: Error loading hardware folder /Users/.../Arduino/hardware/microbridge
  No valid hardware definitions found in folder microbridge.

**Comment by Apollon77** [comment]
When I move the programmertxt and board.txt to the awaited dir according to error message the next warning is:

Board microbridge:bootloaders:microbridge doesn't define a 'build.board' preference. Auto-set to: BOOTLOADERS_MICROBRIDGE

But the "board" is shown in the Board list ... more I will try tomorrow :-)

**Comment by Mesger1** [comment]
It could be some things have changed in the newer version of arduino ide. I
was using 1.0.6

**Comment by Apollon77** [comment]
I found that:http://www.lydiard.plus.com/chapter14.htm

**Comment by Mesger1** [comment]
new arduino not supported

**Comment by j54n1n** [comment]
I have created a PR with the updated board definition in case someone needs this
