### ISSUE TITLE
Winznet Ethernet Shield

### ISSUE THREAD

**Issue by tcubells** [FleetProbe/MicroBridge-Arduino-ATMega2560#4]
We have tested with arduino ethernet shield W5100 and works perfectly

Other tests with Wiznet ethernet shield W5500  fail.
After loading a new BIN from SD card, you must remove power ATmega2560 to work again.

Is there any way to run Wiznet ethernet Shield W5500?
You have to use some specific library?

**Comment by Mesger1** [comment]
you have to set the CS pin accordingly, this pin differs from shield to shield
