### ISSUE TITLE
Not able to update from firmware.bin

### ISSUE THREAD

**Issue by FreedomLabsIO** [FleetProbe/MicroBridge-Arduino-ATMega2560#5]
Hi @gerdmestdagh !

I've formatted a SD Card with a 2 GB partition (although it doesn't seem necessary) (also tried with 16 gb partition) (i've tried 2 different 16 GB Micro SDHC cards)
Put a "firmware.bin" file in root of SD.
Set EEPROM 0x1FF to 0xF0. (verified)
Activate watchdog and reset device (verified).
But device is never updated with the firmware.bin file.

SD Pinout is ok (pins 50, 51, 52 and 53) (PORTB,3 -> PORTB,0).

I burned the MicroBridge bootloader using a Arduino UNO as a "Arduino ISP".

Anything else i should do ?
No errors occurs and i can program my mega2560 normally using ArduinoIDE

Is there a way to check if it's successfully mounting the SD partition and able to list files ?

**Comment by Mesger1** [comment]
you should look to set the correct cs pins in the bootloader code. It
varies between different shields. which shield are you using ?

**Comment by FreedomLabsIO** [comment]
Sorry @gerdmestdagh , i was using the wrong CS pin in code (schematic was a little confusing). I'm using a custom made board. Now it worked !! Thank you !

**Comment by brunoaduarte** [comment]
@gerdmestdagh , now i have a problem with the "flashstartexample.ino". The `wdt_reset()` is not triggering the bootloader code (it jumps directly to the app again and never gets updated). It only works if i do a physical reset (firmware.bin is successfully loaded). Any ideas ?

**Comment by Mesger1** [comment]
glad to hear you figured it out :)
