### ISSUE TITLE
can't define PORTH

### ISSUE THREAD

**Issue by Mzeron** [FleetProbe/MicroBridge-Arduino-ATMega2560#6]
//sparkfun microsd (arduino-pin8)
#define	DDR_CS	_SFR_IO_ADDR(DDRH), 5 	// MMC CS pin (DDR, PORT)
#define	PORT_CS	_SFR_IO_ADDR(PORTH), 5

I trying to configure the sparkfun shield to work but I'm getting a 
asmfunc.S:44: Error: number must be positive and less than 32

**Comment by Mesger1** [comment]
which arduino are you using?

**Comment by Mzeron** [comment]
mega 2560

**Comment by Mesger1** [comment]
what is line 44 is asmfunc.S ?

**Comment by kernel64bits** [comment]
@Mzeron I came through the same problem and managed to solve it, have a look here: https://github.com/FleetProbe/MicroBridge-Arduino-ATMega2560/issues/12#issuecomment-464353438
