### ISSUE TITLE
EEPROM empty after flashing over SD

### ISSUE THREAD

**Issue by timoxd7** [FleetProbe/MicroBridge-Arduino-ATMega2560#9]
I took the file from the built folder (.elf) and it flashed it perfectly (the firmware.bin), but it also deletes the whole EEPROM. If i flash over USB, it doesn't delete it (over the Arduion IDE/VSCode).

**Comment by kawasakizx10rr** [comment]
Did you get it to update from the SD card, i have flashed the bootloader to my mega2560 and when i set the eeprom to 0xF0 and reset the mega the LED blinks on for 6 secs and off for a half a second and it never boots to the code, unless I unplug the SD card OR set the eeprom back to 0xFF ?? Any Idea what's going on please.
